### ISSUE TITLE
ReporterCLI parameters call error

### ISSUE THREAD

**Issue by chrishuges** [compomics/reporter#5]
Not sure if you are interested in hearing about errors in the CLI version of Reporter, but I have been playing around with the CLI version a bit on a linux cluster. 

But just in case, just when trying to look up some more detailed input parameters:

java -cp /projects/ptx_analysis/chughes/software/reporter_apr2018/Reporter-0.7.9/Reporter-0.7.9.jar eu.isas.reporter.cli.ReporterCLIParameters
Error: Main method not found in class eu.isas.reporter.cli.ReporterCLIParameters, please define the main method as:
   public static void main(String[] args)

**Comment by hbarsnes** [comment]
Hi,

The command line support for Reporter is still in beta mode, but in any case it seems like you are using the wrong class. Try with ReporterCLI instead. Not sure how much the Reporter command line has been tested though. Which is why there is no do documentation for it yet, :)

Also note that Reporter is not yet compatible with the latest PeptideShaker version.

Best regards, 
Harald

**Comment by chrishuges** [comment]
Thanks. I was trying to call the parameters class so I could get more details regarding the format for some of the parameter flags. Calling ReporterCLI works. No worries about the documentation...I will keep poking around.  

Should any version of SearchGUI that predates PeptideShaker ver .12 in theory work with that version of peptideshaker? I seem to be getting some errors depending on which searchgui I use with ver. 12 of peptideshaker. 

Cheers,
Chris

**Comment by hbarsnes** [comment]
Hi Chris,

> Should any version of SearchGUI that predates PeptideShaker ver .12 in theory work with that version of peptideshaker?

I think you should be safe with SearchGUI v3.2.20. Anything newer (or older) might result in errors due to using differnet backends.

Best regards,
Harald
